---
version: 2
jobs:
  build:
    docker:
      - image: golangci/golangci-lint:v1.23.3

    steps:
      - checkout

      # lint with the configuration from .golangci.yml
      - run: |
          golangci-lint run ./...

      # vendor and build
      - run: go mod vendor
      - run: go vet   -v       $(go list ./... | grep -v /vendor/)
      - run: go build -v       $(go list ./... | grep -v /vendor/)
      - run: go test  -v -race $(go list ./... | grep -v /vendor/)

      # testing and code coverage
      - run: |
          echo "" > coverage.txt
          for PACKAGE in $(go list ./... | grep -v vendor); do
            go test -race -coverprofile=profile.out -covermode=atomic ${PACKAGE}
            if [ -f profile.out ]; then
              cat profile.out >> coverage.txt
              rm -f profile.out
            fi
          done
      - run: bash <(curl -s https://codecov.io/bash)